### ISSUE TITLE
[Question]Replace BAS45AL by something else ?

### ISSUE THREAD

**Issue by Twisty59** [jbilander/Amiga_500_cpu_relocator_with_2mb_sram#1]
Hello,

I'm building this awesome board right now but unfortunately I can't get the BAS45AL diode to my local electronic supply store.
Is it possible to replace with something else ?

Thanks

**Comment by jbilander** [comment]
Hello, Yes you can replace with a similar spec Low-leakage current switching diode (SOD-80 package). In fact I think it's not needed and you could just solder blob across pads or solder in a Zero Ohm resistor. I haven't tried it myself though. To play it safe replace with a similar diode. Best of luck. -jb

**Comment by Twisty59** [comment]
Hello
I will try to find a similar diode to replace.
Thanks you so much for your reply and sharing with us your project !
